# Generated by Django 2.2.7 on 2019-11-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('version', models.IntegerField()),
                ('ip_len', models.IntegerField()),
                ('ip_type', models.IntegerField()),
                ('ip_all_len', models.IntegerField()),
                ('ip_id', models.IntegerField()),
                ('ip_flags', models.IntegerField()),
                ('ip_ttl', models.IntegerField()),
                ('ip_num', models.IntegerField()),
                ('ip_crc', models.IntegerField()),
                ('ip_src', models.CharField(max_length=15)),
                ('ip_dst', models.CharField(max_length=15)),
                ('ip_ofst', models.IntegerField()),
                ('protocol', models.IntegerField()),
                ('tcp_src', models.IntegerField()),
                ('tcp_dst', models.IntegerField()),
                ('tcp_num', models.IntegerField()),
                ('tcp_ack', models.IntegerField()),
                ('tcp_ofst', models.IntegerField()),
                ('tcp_reserv', models.IntegerField()),
                ('tcp_flag', models.IntegerField()),
                ('tcp_win', models.IntegerField()),
                ('tcp_crc', models.IntegerField()),
                ('tcp_ptr', models.IntegerField()),
                ('tcp_data', models.CharField(max_length=255)),
                ('udp_src', models.IntegerField()),
                ('udp_dst', models.IntegerField()),
                ('udp_len', models.IntegerField()),
                ('udp_crc', models.IntegerField()),
                ('udp_data', models.CharField(max_length=255)),
                ('icmp_type', models.IntegerField()),
                ('icmp_code', models.IntegerField()),
                ('icmp_crc', models.IntegerField()),
                ('icmp_data', models.CharField(max_length=255)),
            ],
        ),
    ]
